### ISSUE TITLE
Ping Link

### ISSUE THREAD

**Issue by justingreerbbi** [keesiemeijer/WordPress-moderator-tools#12]
Add quick link next to username in threads. When clicked, it places “@username” in the textarea for fast ping.

**Comment by anevins12** [comment]
Should it be an icon?

**Comment by anevins12** [comment]
Or just hash character?

**Comment by keesiemeijer** [comment]
Maybe just the "@" character after the user name.

**Comment by justingreerbbi** [comment]
I am not sure. I would think a icon or something very simple would be ideal. There is not too much space there and we don't want to clutter it to much. The @ symbol could be about right.

**Comment by justingreerbbi** [comment]
Maybe something like the attached? 

![screen-shot](https://cloud.githubusercontent.com/assets/4920929/11148270/b564aad6-89e9-11e5-96e8-f58b8716c35a.png)

**Comment by anevins12** [comment]
Yes the custom title would probably be better to target, as that doesn't change

**Comment by justingreerbbi** [comment]
Thats kinda what I was thinking. We really only want to feature for members anyways.

**Comment by anevins12** [comment]
Should be simple as https://gist.github.com/anevins12/a950645e4ac18f64d79f

**Comment by keesiemeijer** [comment]
Looks good. We should get the user name from the first `<strong>` element as it can be different from the name in the url. So, is anyone up for it, or should I add it?

**Comment by anevins12** [comment]
Is the <strong> element holding the username? The idea with pinging someone via their username is that person being pinged gets an email notification

**Comment by keesiemeijer** [comment]
Aha, good to know. I never looked at the username in the link when using the @ link.

**Comment by anevins12** [comment]
Sometimes it doesn't quite work from the slug actually, like some usernames have uppercase & spaces/ periods

**Comment by justingreerbbi** [comment]
Examples?

**Comment by anevins12** [comment]
Period: https://wordpress.org/support/profile/nicolapeluchetti
Space: https://wordpress.org/support/profile/jeffrey-wilcox

**Comment by anevins12** [comment]
Might be safer scraping the profile page for the username

**Comment by justingreerbbi** [comment]
Why would we not be able to just parse the member hyper link and split "/" and get the username for the ping? From what I understand the ping only works on the slug of the user anyways.

**Comment by keesiemeijer** [comment]
@justingreerbbi 

I see you have a different display name as your profile name. What is your  `WordPress.org username` in the profile notifications screen?

https://profiles.wordpress.org/justingreerbbi/profile/notifications/

**Comment by justingreerbbi** [comment]
My display name is "Justin Greer" but my username is "justingreerbbi"

**Comment by keesiemeijer** [comment]
Yeah, I think we can get the username from the link. Here is a not yet minified version you can use to check if it works as expected
https://github.com/keesiemeijer/WordPress-moderator-tools/blob/master/WordPress_Moderator_Tools_Chrome.user.js

Click the Raw button to install it.

**Comment by anevins12** [comment]
The ping comes from an exact match from the username, not the slug name. I've confirmed with Otto. Also note that usernames are case sensitive.

**Comment by anevins12** [comment]
Also usernames that have spaces cannot be pinged, to keep in mind when testing.

**Comment by keesiemeijer** [comment]
So, for example with justingreerbbi, we should use display name `@Justin Greer` that's stored in the `<strong>` element.

**Comment by keesiemeijer** [comment]
[this should do it](https://github.com/keesiemeijer/WordPress-moderator-tools/blob/3c05600062510aa50386b32c2cdb0e6bfb64f8c9/WordPress_Moderator_Tools_Chrome.user.js#L618-L639)

It uses the user_nicename from the strong element.
