### ISSUE TITLE
Ping feedback

### ISSUE THREAD

**Issue by anevins12** [keesiemeijer/WordPress-moderator-tools#13]
It might just be me because I suffer from a small level of dyslexia, but the "@ping" text slightly clutters the user info in a thread and reduces the readability of that info (only slightly). I'm sure I could get used to it. We could always go with the single '@' character if it's an issue for others.

**Comment by keesiemeijer** [comment]
Yeah, It feels a bit cluttered. I'm all for just the '@' character as there is also the '#' link for the permalink of a post. And maybe even move it before or after the username instead of where it is now.

**Comment by keesiemeijer** [comment]
Try this out for just the '@' character. (click the Raw button)
https://github.com/keesiemeijer/WordPress-moderator-tools/blob/ping-link/WordPress_Moderator_Tools_Chrome.user.js

I think it's much better

**Comment by anevins12** [comment]
That's cool, I'm happy with this

**Comment by keesiemeijer** [comment]
Should be fixed in 5.0.1
https://keesiemeijer.github.io/WordPress-moderator-tools/#keyboard-navigation
