### ISSUE TITLE
The @ ping link uses displayname over username

### ISSUE THREAD

**Issue by Clorith** [keesiemeijer/WordPress-moderator-tools#17]
Using the @ ping reference can be dodgy as users have spaces in their display names.

We should probably change this to use the username instead, extracting it from the profile URL seems like the simplest approach and `.authortitle > a.href` seems like a good contender for this purpose

**Comment by keesiemeijer** [comment]
There is a lot of confusion in #12 what should be used. Do you know if  the `.authortitle > a.href` username is used  for the matches?

**Comment by keesiemeijer** [comment]
It seems `.authortitle > a.href` is used
https://wordpress.slack.com/archives/forums/p1471009892005726

When I find some time I will update it to use the user name slug

**Comment by keesiemeijer** [comment]
Fixed in verson [5.0.8](https://github.com/keesiemeijer/WordPress-moderator-tools/releases/tag/5.0.8)
