### ISSUE TITLE
Potential bug with Bulk Actions in BBAdmin

### ISSUE THREAD

**Issue by anevins12** [keesiemeijer/WordPress-moderator-tools#7]
If you remove posts from the spam queue, those posts ("legit posts") disappear from view without a page refresh. 
Then if you do the Delete bulk action and TICK ALL posts, you actually end up deleting the legit posts. 

I guess the legit posts that were removed from view were actually still tickable in the DOM.

**Comment by keesiemeijer** [comment]
This should be fixed in version 4
https://github.com/keesiemeijer/WordPress-moderator-tools/blob/master/WordPress_Moderator_Tools_Chrome.user.js#L759
